export const AppRoutes = {
  client: {
    Home: '/',
    AboutMe: '/about-me',
    News: '/news',
    Projects: '/projects',
    newsDetails: (uuid: string) => `/news/${uuid}`,
    projectDetails: (uuid: string) => `/projects/${uuid}`,
  },
  admin: {
    Admin: '/admin',
    AdminProjects: '/admin/projects',
    AdminSettings: '/admin/settings',
    AdminArticles: '/admin/articles',
    AdminArticlesNew: '/admin/articles/new',
    AdminCv: '/admin/cv',
    AdminCvEmploymentTypes: '/admin/cv/employment-types',
    AdminCvExperience: '/admin/cv/experience',
    AdminCvLanguages: '/admin/cv/languages',
    AdminCvLinks: '/admin/cv/links',
    AdminCvPreview: '/admin/cv/preview',
    AdminCvProfile: '/admin/cv/profile',
    AdminCvProfileNew: '/admin/cv/profile/new',
    AdminCvProjects: '/admin/cv/projects',
    AdminCvSkills: '/admin/cv/skills',
    AdminCvTemplates: '/admin/cv/templates',
    AdminCvVersions: '/admin/cv/versions',
  },
  api: {
    Health: '/api/health',
    Projects: '/api/projects',
    Articles: '/api/articles',
    CvProfiles: '/api/cv/profiles',
    CvProfilesActive: '/api/cv/profiles/active',
    cvProfileByUuid: (uuid: string) => `/api/cv/profiles/${uuid}`,
  }
}
